#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " name
nomer=$(cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name |awk -F : '{print $7}')
if [[ "$nomer" = "/bin/false" ]]
then
clear
echo " "
echo " "
echo -e "\033[44;1;37m O que vc deseja redefinir para \033[1;33m$name \033[44;1;37m?\033[0m
\033[1;32m
  1) Numero de logins
  2) Data de expiraçao
  3) Mudar senha do usuario
  4) Deletar usuario
  5) Deletar e desconectar todos do usuario
  6) Desconectar todos do usuario\033[0m"
else
echo " "
echo " "
echo -e "\033[1;31m Usuario \033[0;31m$name\033[1;31m nao existe\033[0m"
echo " "
exit
fi

read -p "opção: " option

if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
rm /etc/tempo/$name.sh /dev/null 2>/dev/null
limit $name $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo $name >> "/etc/cache202.sh"
cache201.sh
exit
fi
if [ $option -eq 3 ]; then
read -p "Qual a nova senha para $name: " senha
(echo "$senha" ; echo "$senha" ) |passwd $name > /dev/null 2>/dev/null
rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$name
echo "Nova senha aplicada"
exit
fi

 if [ $option -eq 4 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
 echo "Usuario $name foi deletado"
 exit
 fi

 if [ $option -eq 5 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi deletado e parado"
 exit
 fi

 if [ $option -eq 6 ]; then
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi parado"
 exit
 fi
echo -e "\033[1;31mEsta opcao nao existe\033[0m"
