#!/bin/bash

read -p "Qual usuario vc deseja ver detalhes? " users
if cat /etc/passwd |grep $users: > /dev/null
then
echo " "
else
echo " "
echo -e " \033[0;31mUsuario $users não existe\033[0m"
echo " "
exit
fi

clear
if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi

if  senha=$(cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi

if  IP=$(cat /bin/IPVPS > /dev/null 2> /dev/null)
then
IP=$(wget -qO- ipv4.icanhazip.com)
fi

usernum=$(ps -u $users |grep sshd |wc -l)

data1=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $1}')
data2=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $2}')
data3=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $3}')

clear
echo -e "\033[1;32m##########################################"
echo -e "
\033[1;36m Usuario: \033[2;37m$users
\033[1;36m Senha: \033[2;37m$senha
\033[1;36m Limite de conexoes: \033[2;37m$limitecs
\033[1;36m Data de expiração: \033[2;37m$data3/$data2/$data1
\033[1;36m IP do Servidor SSH: \033[2;37m$IP
\033[1;36m Porta SSH: \033[2;37m22 \033[1;36mou \033[2;37m443
\033[1;36m IP da Proxy: \033[2;37m$IP
\033[1;36m Porta Proxy: \033[2;37m80 \033[1;36mou \033[2;37m8080 \033[1;36mou \033[2;37m3128
"
if [ $usernum -eq 0 ]; then

echo -e "\033[1;36m Status atual: \033[1;31mOffline"
else
echo -e "\033[1;36m Status atual: \033[1;32mOnline"
fi

if [ $usernum -eq 0 ]; then
echo -e "\033[1;36m Numero Conexoes Online: \033[1;31m$usernum
"
else
echo -e "\033[1;36m Numero Conexoes Online: \033[1;32m$usernum
"
fi

echo -e "\033[1;32m##########################################\033[1;0m"
echo "
"
