#!/bin/bash
clear

echo -e "\033[1;30m------------------------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuario               Senha               Data E.          Logins S.   Conexoes S.  \033[0m"
echo -e "\033[1;30m------------------------------------------------------------------------------------\033[0m"
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do

if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi

if  senha=$(cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi

data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
date="Nunca"
fi

usertotal=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- | wc -l)

calculo=$(ps x | grep "sshd:" |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi grep --color=auto |grep -vi @pts/ |grep -vi accepted |wc -l)

usernum=$(ps -u $users |grep sshd |wc -l) 2> /dev/null
detalhesdata=$(printf '%-18s' "$data")
detalheslimit=$(printf '%-10s' "$limitecs")
detalhes=$(printf ' %-21s' "$users")
detalhespass=$(printf '%-18s' "$senha")
if [ $usernum -eq 0 ]; then
echo -e "\033[1;33m$detalhes $detalhespass $detalhesdata   $detalheslimit \033[1;31m  $usernum\033[0m"
else
echo -e "\033[1;33m$detalhes $detalhespass $detalhesdata   $detalheslimit \033[1;32m  $usernum\033[0m"
fi
echo -e "\033[1;30m------------------------------------------------------------------------------------\033[0m"
done
echo -e "\033[1;33mTotal: $usertotal     Online: \033[1;32m$calculo\033[0m"
