#!/bin/bash
clear
echo " "
echo -e " \033[44;1;37m O que vc deseja Atualizar ?\033[0m

\033[1;32m  1) Atualizar VpsPack
  2) Atualizar Configurações
  3) Atualizar Tudo\033[0m"
echo " "
read -p " opção: " option

echo "   Atualizando..."

cd 
if [ $option -eq 1 ]; then
rm VpsPack-install /dev/null 2>/dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/VpsPack-install && bash VpsPack-install
rm VpsPack-install /dev/null 2>/dev/null
chmod 711 /bin/*
chmod 715 /bin/pack
clear
echo " "
echo -e "\033[0;32mVpsPack Atualizado com Sucesso\033[0m"
exit
fi

if [ $option -eq 2 ]; then
rm configuracao 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/configuracao && bash configuracao
rm configuracao 2> /dev/null
chmod 710 /etc .
clear
echo " "
echo -e "\033[0;32mConfigurações Atualizadas com Sucesso\033[0m"
exit
fi

if [ $option -eq 3 ]; then
rm OpenVPN-pack 2> /dev/null 
rm configuracao 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/VpsPack-install && bash VpsPack-install
wget https://raw.githubusercontent.com/matheuslarcher20/Install/master/configuracao && bash configuracao
rm OpenVPN-pack 2> /dev/null 
rm configuracao 2> /dev/null
chmod 710 /etc .
chmod 711 /bin/*
chmod 715 /bin/pack
clear
echo " "
echo -e "\033[0;32mVps Atualizado com Sucesso\033[0m"
exit
fi

echo -e "\033[1;31messa opçao não existe\033[0m"

