#!/bin/bash
clear
echo " "
echo -e " \033[44;1;37m O que vc deseja Atualizar ?\033[0m

\033[1;32m  1) Atualizar OpenVPN
  2) Atualizar Configurações
  3) Atualizar Tudo\033[0m"
echo " "
read -p " opção: " option

echo "   Atualizando..."


if [ $option -eq 1 ]; then
rm /root/VpsPack-install 2> /dev/null
https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/OpenVPN-pack && bash OpenVPN-pack
clear
echo " "
echo -e "\033[0;32mOpenVPN Atualizado com Sucesso\033[0m"
exit
fi

if [ $option -eq 2 ]; then
rm /root/configuracao 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/configuracao && bash configuracao
clear
echo " "
echo -e "\033[0;32mConfigurações Atualizadas com Sucesso\033[0m"
exit
fi

if [ $option -eq 3 ]; then
rm /root/VpsPack-install 2> /dev/null 
rm /root/configuracao 2> /dev/null
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/OpenPack
clear
echo " "
echo -e "\033[0;32mVps Atualizado com Sucesso\033[0m"
exit
fi

echo -e "\033[1;31messa opçao não existe\033[0m"

