#!/bin/bash
clear
echo " "
echo -e " \033[44;1;37m O que vc deseja Atualizar ?\033[0m

\033[1;32m  1) Atualizar VpsPack
  2) Atualizar Configurações
  3) Atualizar Tudo\033[0m"
echo " "
read -p " opção: " option

echo "   Atualizando..."


if [ $option -eq 1 ]; then
rm /root/VpsPack-install
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/VpsPack-install && bash VpsPack-install
clear
echo " "
echo -e "\033[0;32mVpsPack Atualizado com Sucesso\033[0m"
exit
fi

if [ $option -eq 2 ]; then
wget https://raw.githubusercontent.com/matheuslarcher20/configuracao/master/configuração && bash configuração
clear
echo " "
echo -e "\033[0;32mConfigurações Atualizadas com Sucesso\033[0m"
exit
fi

if [ $option -eq 3 ]; then
wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/install && bash install
clear
echo " "
echo -e "\033[0;32mVps Atualizado com Sucesso\033[0m"
exit
fi

echo -e "\033[1;31messa opçao não existe\033[0m"

