#!/bin/bash
VALID=$(ps x | grep "sshd:" | grep pts | grep -vi color)
if [[ $VALID = '' ]]; then
echo ""
exit
else
rm /etc/detalhesusers.cache.old > /dev/null 2> /dev/null
fi
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn`
do
if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi
if (cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi
data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
date="Nunca"
fi
if (cat /etc/openvpn/openvpn-status.log > /dev/null 2> /dev/null)
then
usersvpn=$(cat /etc/openvpn/openvpn-status.log |grep -w $users| grep 10.8 | awk -F , '{print $2}')
else
usersvpn=''
calculovpn=''
fi
usernum=$(ps -u $users |grep sshd |wc -l)
if [[ $usersvpn = $users ]]; then
status='Online'
else
status='Offline'
fi
echo "$users:$senha:$data:$usernum:$limitecs:$status" >> /etc/detalhesusers.cache.old
done
cp /etc/detalhesusers.cache.old /etc/detalhesusers.cache
