#!/bin/bash
criar-apagar /dev/null 2>/dev/null
exserverUsers /dev/null 2>/dev/null
VALID=$(ps x | grep "sshd:" | grep -vi color)
if [[ $VALID = '' ]]; then
echo "" 1> /dev/null
exit
else
echo "" 1> /dev/null
fi
VALID2=$(cat /etc/detalhesusers.cache.valid 2> /dev/null)
if [[ $VALID2 = "" ]]
then
echo "" 1> /dev/null
else
echo "" 1> /dev/null
exit
fi
echo "ok" >> /etc/detalhesusers.cache.valid
detalhesusers.xp > /dev/null 2> /dev/null
echo "#!/bin/bash" >> /etc/detalhesusers.cache.old
echo "clear" >> /etc/detalhesusers.cache.old
echo 'echo -e "' >> /etc/detalhesusers.cache.old
echo "-------------------------------------------------------
 Usuario       Senha        Data E.       SSH      VPN
-------------------------------------------------------" >> /etc/detalhesusers.cache.old

for users in `cat /etc/activeuser.txt|sort`
do
if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi
if (cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi
data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
#dataxp=$(cat /etc/expireduser.txt |grep -w $users |awk '{print $3}')
data7xp=$(cat /etc/infouser.txt |grep -w $users |awk '{print $3}')
if [[ $data7xp = $users ]]
then
data="\033[0;33m$data"
fi
#if [[ $dataxp = $users ]]
#then
#data="\033[0;31m$data"
#fi
if [[ $data = never ]] 2> /dev/null
then
data="Nunca"
fi
usertotal=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn| wc -l)
calculo=$(ps x | grep "sshd:" |grep "priv" |grep -vi root |wc -l)
if (cat /etc/openvpn/openvpn-status.log > /dev/null 2> /dev/null)
then
usersvpn=$(cat /etc/openvpn/openvpn-status.log |grep -w $users| grep 10.8 | awk -F , '{print $2}')
calculovpn=$(cat /etc/openvpn/openvpn-status.log | grep 10.8 | cut -d "," -f 2 | wc -l)
else
usersvpn=''
calculovpn=''
fi
usernum=$(ps -u $users |grep sshd |wc -l)
detalhesdata=$(printf '%-13s' "$data")
detalheslimit=$(printf '%-4s' "$limitecs")
detalhes=$(printf ' %-13s' "$users")
detalhespass=$(printf '%-11s' "$senha")

if [[ $usersvpn = $users ]]; then
status='\033[1;32mOn'
else
status='\033[1;31mOff'
fi
if [ $usernum -eq 0 ]; then
usernum="\033[1;31m$usernum"
else
usernum="\033[1;32m$usernum"
fi
echo "\033[1;33m$detalhes $detalhespass $detalhesdata  $usernum\033[2;37m \ \033[1;33m$detalheslimit $status\033[0m" >> /etc/detalhesusers.cache.old
echo "\033[1;30m-------------------------------------------------------\033[0m" >> /etc/detalhesusers.cache.old
echo "$users:$usernum:$status" >> /etc/status.old
done
echo "\033[1;33mTotal: $usertotal     Online(SSH): \033[1;32m$calculo    \033[1;33mOnline(OpenVPN): \033[1;32m$calculovpn\033[0m" >> /etc/detalhesusers.cache.old
data=$(date "+%d/%m/%Y %T")
datacache=$(date "+%s")
echo "Ultima atualizacao: $data" >> /etc/detalhesusers.cache.old
echo '"' >> /etc/detalhesusers.cache.old
validadorADM=$(cat /etc/passwd|awk -F : '{print $1}')
dataxpADM=$(cat /etc/expireduser.txt|awk '{print $3}')
echo "$validadorADM" > /clientes/validador.txt
echo "$dataxpADM" > /clientes/dataxp.txt
mv /etc/detalhesusers.cache.old /etc/detalhesusers.cache > /dev/null 2> /dev/null
mv /etc/status.old /clientes/status > /dev/null 2> /dev/null
echo "$datacache" > /etc/data.cache
rm /etc/detalhesusers.cache.valid > /dev/null 2> /dev/null
