#!/bin/bash
for user in `cat /clientes/criar|awk -F : '{print $1}'`
do
senha=$(cat /clientes/criar | grep -w $user |awk -F : '{print $2}')
date=$(cat /clientes/criar | grep -w $user |awk -F : '{print $4}')
limite=$(cat /clientes/criar | grep -w $user |awk -F : '{print $3}')
ADM=$(cat /clientes/criarADM$user)
if cat /etc/passwd |grep -w $user: 1> /dev/null 2>/dev/null
then
echo "" 1> /dev/null
else
  useradd -M -s /bin/false $user
  (echo $senha ; echo $senha) | passwd $user > /dev/null 2> /dev/null
  limit $user $limite 1> /dev/null 2> /dev/null
  echo "$senha" > /etc/VpsPackdir/senha/$user
  chage -E $date $user 2> /dev/null
  echo "$date" > /etc/VpsPackdir/date/$user
echo "$ADM" > /etc/VpsPackdir/UsuariosADM/$user
fi
done
rm /clientes/criar > /dev/null 2> /dev/null
rm /clientes/criarADM$user > /dev/null 2> /dev/null
if [ -e /clientes/apagar ]
then
echo ""
else
for name in `cat /clientes/apagar|awk -F : '{print $1}'`
do
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
rm /clientes/criarADM$name /dev/null 2>/dev/null
rm /etc/VpsPackdir/UsuariosADM/$name /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
done
rm /clientes/apagar > /dev/null 2> /dev/null
fi
for userd in `cat /clientes/editar|awk -F : '{print $1}'`
do
senha=$(cat /clientes/editar | grep -w $userd |awk -F : '{print $2}')
date=$(cat /clientes/editar | grep -w $userd |awk -F : '{print $4}')
limite=$(cat /clientes/editar | grep -w $userd |awk -F : '{print $3}')
  (echo $senha ; echo $senha) | passwd $userd > /dev/null 2> /dev/null
  limit $userd $limite 1> /dev/null 2> /dev/null
  echo "$senha" > /etc/VpsPackdir/senha/$userd
  chage -E $date $userd 2> /dev/null
  echo "$date" > /etc/VpsPackdir/date/$userd
done
rm /clientes/editar > /dev/null 2> /dev/null
