#!/bin/bash
nomecoment=$(echo VIVO🇧🇷)
newclient () {
        # Generates the custom client.ovpn
        cp /etc/openvpn/client-common.txt ~/$nomecoment'-'$1.ovpn
        echo "<ca>" >> ~/$nomecoment'-'$1.ovpn
        cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$nomecoment'-'$1.ovpn
        echo "</ca>" >> ~/$nomecoment'-'$1.ovpn
        echo "<cert>" >> ~/$nomecoment'-'$1.ovpn
        cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$nomecoment'-'$1.ovpn
        echo "</cert>" >> ~/$nomecoment'-'$1.ovpn
        echo "<key>" >> ~/$nomecoment'-'$1.ovpn
        cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$nomecoment'-'$1.ovpn
        echo "</key>" >> ~/$nomecoment'-'$1.ovpn
        echo "<tls-auth>" >> ~/$nomecoment'-'$1.ovpn
        cat /etc/openvpn/ta.key >> ~/$nomecoment'-'$1.ovpn
        echo "</tls-auth>" >> ~/$nomecoment'-'$1.ovpn
}

                    echo ""
                        echo -e "\033[1;32m Diga-me um nome para o novo certificado\033[0m"
                        read -p " Nome: " CLIENT
                        cd /etc/openvpn/easy-rsa/
                        VALIDADOR=$(cat /etc/openvpn/easy-rsa/pki/issued/$CLIENT.crt > /dev/null 2> /dev/null)
                        if [[ $VALIDADOR = "" ]]; then
                        echo " "
                        else
                        echo -e "
\033[0;31mUm certificado com o nome:\033[1;31m $CLIENT \033[0;31mja existe!!\033[0m
"
                        exit
                       fi

                       ./easyrsa build-client-full $CLIENT nopass
                        # Generates the custom client.ovpn
                        newclient "$CLIENT"
                        VALIDADOR2=$(cat /etc/openvpn/easy-rsa/pki/issued/$CLIENT.crt)
                        if [[ $VALIDADOR2 = "" ]]; then
                        echo -e "
\033[0;31m Erro ao gerar certificado para: $CLIENT !!\033[0m"
else
                        echo " "
                        echo -e "\033[1;36m Novo certificado foi gerado para: \033[1;37m$CLIENT\033[0m"
                        echo " "
                        echo -e "\033[1;36m Seu arquivo está disponivel em \033[1;37m" ~/"Vivo_BR_$CLIENT.ovpn\033[0m"
                     fi
exit
