#!/bin/bash
echo "Desinstalando..."
rm /bin/VpsPack1
rm /bin/UserBack1
rm -r /etc/usuarios /etc/tempo1
rm /bin/Usercreate1
rm /bin/UserRedefine1
rm /bin/Monitoring1
rm /bin/Detalhes1
rm /bin/limit1
rm /etc/firewall-block1
rm /etc/ResetFirewall1
rm /etc/add-host1
rm /etc/install-addhost1
rm /etc/Desinstalar1
clear
echo -e "\033[0;31mvocê não tem permissão para desinstalar o VpsPack\033[0m"
