#!/bin/bash
bash /etc/detalhesusers.cache
data=$(date "+%s")
datacache=$(cat /etc/data.cache)
datareal=$(($data - $datacache))
if [[ $datareal -gt 200 ]]
then
badvpn start
clear
echo -e " \033[1;32mcache-detalhesusers.install foi instalado com sucesso!! Fexe essa sessão e inicie uma nova. \033[0m"
screen -S detalhesusers cache-detalhesusers.install
exit
else
cache-detalhesusers
bash /etc/detalhesusers.cache
fi
