#!/bin/bash
clear

echo -e "\033[1;30m----------------------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuario          Senha        Data E.        Logins(SSH)  Status(OpenVPN)  \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------------------\033[0m"
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn`
do

if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi

if  senha=$(cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi

data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
date="Nunca"
fi

usertotal=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn| wc -l)
calculo=$(ps x | grep "sshd:" |grep "priv" |grep -vi root |wc -l)
usersvpn=$(cat /etc/openvpn/openvpn-status.log | grep 10.8 | cut -d "," -f 2)

usernum=$(ps -u $users |grep sshd |wc -l) 2> /dev/null
detalhesdata=$(printf '%-15s' "$data")
detalheslimit=$(printf '%-8s' "$limitecs")
detalhes=$(printf ' %-16s' "$users")
detalhespass=$(printf '%-9s' "$senha")
calculovpn=$(cat /etc/openvpn/openvpn-status.log | grep 10.8 | cut -d "," -f 2 | wc -l)
if [[ $usersvpn = $users ]]; then
status='\033[1;32mOnline'
else
status='\033[1;31mOffline'
fi
if [ $usernum -eq 0 ]; then

echo -e "\033[1;33m$detalhes  $detalhespass  $detalhesdata    \033[1;31m$usernum\033[2;37m \ \033[1;33m$detalheslimit  $status\033[0m"

else
echo -e "\033[1;33m$detalhes  $detalhespass  $detalhesdata    \033[1;32m$usernum\033[2;37m \ \033[1;33m$detalheslimit  $status\033[0m"
fi
echo -e "\033[1;30m----------------------------------------------------------------------------------\033[0m"
done

echo -e "\033[1;33mTotal: $usertotal     Online(SSH): \033[1;32m$calculo    \033[1;33mOnline(OpenVPN): \033[1;32m$calculovpn\033[0m
"

read -p "Qual usuario vc deseja ver detalhes? " users

nomer=$(cat /etc/passwd |grep $users: |grep -vi [a-z]$users |grep -v [0-9]$users |awk -F : '{print $7}')
if [[ "$nomer" = "/bin/false" ]]
then
echo " "
else
echo -e "
\033[1;31m Usuario \033[0;31m$users\033[1;31m nao existe\033[0m"
echo " "
exit
fi
IP=$(wget -qO- ipv4.icanhazip.com)
if [[ $users = "" ]]; then

echo -e "
 \033[1;36mSeu IP Externo é: \033[2;37m$IP\033[0m
"
exit
else
echo ""
fi
clear
if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi

if  senha=$(cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi

usernum=$(ps -u $users |grep sshd |wc -l)
updown=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $users | cut -d "," -f 3,4)
ipvpn=$(cat /etc/openvpn/openvpn-status.log | grep 10.8 | grep -w $users | cut -d "," -f 1)
desde=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $users | cut -d "," -f 5)
data1=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $1}')
data2=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $2}')
data3=$(cat "/etc/VpsPackdir/date/$users" |awk -F / '{print $3}')

clear
echo -e "\033[1;32m##########################################"
echo -e "
\033[1;36m Usuario: \033[2;37m$users
\033[1;36m Senha: \033[2;37m$senha
\033[1;36m Data de expiração: \033[2;37m$data3/$data2/$data1
\033[1;36m Limite de conexoes(SSH): \033[2;37m$limitecs
\033[1;36m Upload\Download(OpenVPN): \033[2;37m$updown
\033[1;36m IP virtual usuario(OpenVPN): \033[2;37m$ipvpn
\033[1;36m Online Desde: \033[2;37m$desde
\033[1;36m IP do Servidor SSH: \033[2;37m$IP
\033[1;36m Porta SSH: \033[2;37m22 \033[1;36mou \033[2;37m443
\033[1;36m IP da Proxy: \033[2;37m$IP
\033[1;36m Porta Proxy: \033[2;37m80 \033[1;36mou \033[2;37m8080 \033[1;36mou \033[2;37m3128
"
echo -e "\033[1;36m Status atual(OpenVPN): $status "
if [ $usernum -eq 0 ]; then
echo -e "\033[1;36m Numero Conexoes Online(SSH): \033[1;31m$usernum
"
else
echo -e "\033[1;36m Numero Conexoes Online(SSH): \033[1;32m$usernum
"
fi
echo -e "\033[1;32m##########################################\033[1;0m"
echo "
"
