#!/bin/bash
echo -e "\033[40;1;37m VpsPack Detalhes \033[0m
\033[1;33mSempre execute com o usuario root
Vc pode virar root com \033[1;31msu \033[1;33mou \033[1;31msudo su"

echo -e "\033[1;32m
Ferramenta Limit:\033[1;36m

Essa ferramenta monitora o numero de conexoes de usuarios que teve seu limite aplicado
Use essa ferramenta pelo VpsPack (recomendado)
Tbm pode a usar com apenas um comando \033[1;33mlimit usuario limite\033[0m
\033[1;36mAo exceder o limite as conexoes excedentes serao desconectados !!
 
\033[1;32mUserCreate:

\033[1;36mObjetivo criar usuarios de forma rapida e aplicando uma validade em dias
Para executar comando: Usercreate 
Ou execute pelo VpsPack

\033[1;32mUserRedefine:

\033[1;36mFerramenta para redefinir o limite de logins de um usuario ou redefinir a data de expiraçao de um usuario, 
deletar usuarios Forçar o deletamento e tambem desconectar todos de um usuario.
Para executar: UserRedefine
Ou execute pelo VpsPack

\033[1;32mInstall-addhosts & add-hosts:

\033[1;36mA ferramenta Install-addhosts so deve ser usada uma vez ela prepara diretorios para a ferramenta add-hosts

Ferramenta add-hosts ela adiciona novos dominios (hosts payloads) em qualquer tipo de squid.conf

Execute pelo VpsPack

\033[1;32mFirewall-block & firewall-reset:

\033[1;36mFerramenta firewall-block faz o bloqueio torrent e protocolo icmp

Firewall-reset desfaz todas as regras iptables desabilitando qualquer bloqueio no firewall

ATENÇAO ESSAS DUAS FERRAMENTAS PODEM CAUSAR PROBLEMAS EXECUTE POR SUA CONTA
MUITAS EMPRESAS USAM O IPTABLES EM SUAS MAQUINAS VIRTUAIS E ESSE NÃO PODE SER ALTERADO

Execute pelo VpsPack

\033[1;32mMonitoring:

\033[1;36mImportante ferramenta que le mostra quantas conexoes em cada usuario !!

\033[1;32mbackupusers: 

\033[1;36mFaça backup dos usuarios para uma futura restauração

\033[1;36mPara trasfererir os backup para outro servidor execute: 
scp /etc/VpsPackdir/backup root@(IP):/root

\033[1;32mOUTROS:
\033[1;32mPARA RETIRAR O LIMITE DE CONEXOES DE UM USUARIO OU DE TODOS APAGUE

\033[1;36mrm /etc/usuarios/usuario.sh
rm /etc/tempo/usuario.sh

Ou retire o limite de todos

rm -r /etc/tempo /etc/usuarios

\033[1;32mAJUSTAR A HORA DO SERVIDOR:  

\033[1;36mmv /etc/localtime /root/
ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
ver a hora: date

\033[40;1;37mVpsPack\033[0m"
