#!/bin/bash
echo "-------------------------------------------------------
 Usuario       Senha        Data E.       SSH      VPN
-------------------------------------------------------"
for users in `cat usuarios.txt | awk -F : '{print $1}'|sort`
do
senha=$(cat usuarios.txt |grep -w $users| awk -F : '{print $2}')
limite=$(cat usuarios.txt |grep -w $users| awk -F : '{print $3}')
data=$(cat usuarios.txt |grep -w $users| awk -F : '{print $4}')
status=$(cat /clientes/status |grep -w $users|awk -F : '{print $3}')
usernum=$(cat /clientes/status |grep -w $users|awk -F : '{print $2}')
usertotal=$(cat usuarios.txt | awk -F : '{print $1}'|sort| wc -l)
detalhesdata=$(printf '%-13s' "$data")
detalheslimit=$(printf '%-4s' "$limite")
detalhes=$(printf ' %-13s' "$users")
detalhespass=$(printf '%-11s' "$senha")
if [[ $status = "" ]]; then
detalhes="\033[0;31m$detalhes"
detalhespass="\033[0;31mErro!!"
else
senh4=$(cat usuarios.txt)
fi
echo -e "\033[1;33m$detalhes $detalhespass $detalhesdata $usernum\033[2;37m \ \033[1;33m$detalheslimit  $status\033[0m"
echo -e "\033[1;30m-------------------------------------------------------\033[0m"
done
echo -e "\033[1;33m Total: $usertotal\033[0m"
