#!/bin/bash
NUMBEROFCLIENTS=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort|wc -l)
if [[ "$NUMBEROFCLIENTS" = '0' ]]; then
echo ""
echo -e "\033[1;31mVocê não tem usuarios existentes!\033[0m"
exit 6
fi
NUMBEROFCLIENTS=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort| wc -l)
echo -e "\033[44;1;37m      Ver Detalhes do Usuário       \033[0m"
awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort |nl -s ") "
 if [[ "$NUMBEROFCLIENTS" = '1' ]]; then
 read -p "Selecione um usuario [1]: " CLIENTNUMBER
 else
 read -p "Selecione um usuario [1-$NUMBEROFCLIENTS]: " CLIENTNUMBER
 fi
user=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort| sed -n "$CLIENTNUMBER"p)
if (echo $CLIENTNUMBER | egrep '[^0-9]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -gt $NUMBEROFCLIENTS ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -lt 1 ]]; then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
nomer=$(cat /etc/passwd |grep $user: |grep -vi [a-z]$user |grep -v [0-9]$user |awk -F : '{print $7}')
IP=$(cat /etc/Install-IP)
if [[ $user = "" ]]; then
echo -e "
 \033[1;36mSeu IP Externo é: \033[2;37m$IP\033[0m
"
exit
else
echo ""
fi
clear
if cat /etc/VpsPackdir/limite/$user > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$user)
else
limitecs="null"
fi
if (cat /etc/VpsPackdir/senha/$user > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$user)
else
senha="null"
fi
num=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 4|wc -c)
num2=$(($num - 4))
calculoKB=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 4|cut -c1-$num2)
if [[ $num2 -gt 3 ]]
then
num3=$(echo $calculoKB|wc -c)
num4=$(($num3 - 4))
calculoMB=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 4|cut -c1-$num4)
down=$(echo $calculoMB MB)
else
down=$(echo $calculoKB KB)
fi
num10=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 3|wc -c)
num20=$(($num10 - 4))
UcalculoKB=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 3|cut -c1-$num20)
if [[ $num20 -gt 3 ]]
then
num30=$(echo $UcalculoKB|wc -c)
num40=$(($num30 - 4))
UcalculoMB=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 3|cut -c1-$num40)
up=$(echo $UcalculoMB MB)
else
up=$(echo $UcalculoKB KB)
fi
uservpn=$(cat /etc/openvpn/openvpn-status.log |grep -w $user| grep 10.8 | cut -d "," -f 2)
usernum=$(ps -u $user |grep sshd |wc -l)
ipvpn=$(cat /etc/openvpn/openvpn-status.log | grep 10.8 | grep -w $user | cut -d "," -f 1)
desde=$(cat /etc/openvpn/openvpn-status.log | grep -vi 10.8 | grep -w $user | cut -d "," -f 5)
data1=$(cat "/etc/VpsPackdir/date/$user" |awk -F / '{print $1}')
data2=$(cat "/etc/VpsPackdir/date/$user" |awk -F / '{print $2}')
data3=$(cat "/etc/VpsPackdir/date/$user" |awk -F / '{print $3}')
if [[ $uservpn = $user ]]; then
status='\033[1;32mOnline'
else
status='\033[1;31mOffline'
down="0 Bytes"
up="0 Bytes"
fi
ADM=$(cat /etc/VpsPackdir/UsuariosADM/$user|awk '{print $1}')
ADM1=$(cat /etc/VpsPackdir/UsuariosADM/$user|awk '{print $3}')
ADM2=$(cat /etc/VpsPackdir/UsuariosADM/$user|awk '{print $4}')
ADM3=$(cat /etc/VpsPackdir/UsuariosADM/$user|awk '{print $5}')
IPPORT1=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -1 |tail -1)
IPPORT2=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -2|tail -1)
IPPORT3=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -3|tail -1)
IPPORT4=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -4|tail -1)
#IPPORT5=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -5|tail -1)
#IPPORT6=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -6|tail -1)
#IPPORT7=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -7|tail -1)
#IPPORT8=$(cat /etc/squid3/squid.conf |grep -w "http_port" |awk '{print $2}' |head -8|tail -1)
IPSSHPORT1=$(cat /etc/ssh/sshd_config |grep -w "Port" |awk '{print $2}' |head -1 |tail -1)
#IPSSHPORT2=$(cat /etc/ssh/sshd_config |grep -w "Port" |awk '{print $2}' |head -2|tail -1)
#IPSSHPORT3=$(cat /etc/ssh/sshd_config |grep -w "Port" |awk '{print $2}' |head -3|tail -1)
#IPSSHPORT4=$(cat /etc/ssh/sshd_config |grep -w "Port" |awk '{print $2}' |head -4|tail -1)
IPVPNPORT1=$(cat /etc/openvpn/server.conf |grep -w "port" |awk '{print $2}' |head -1 |tail -1)
#IPVPNPORT2=$(cat /etc/openvpn/server.conf |grep -w "port" |awk '{print $2}' |head -2 |tail -1)
#IPVPNPORT3=$(cat /etc/openvpn/server.conf |grep -w "port" |awk '{print $2}' |head -3 |tail -1)
#IPVPNPORT4=$(cat /etc/openvpn/server.conf |grep -w "port" |awk '{print $2}' |head -4 |tail -1)
if [[ "$nomer" = "/bin/false" ]]
then
echo "" > /dev/null
else
user="$user (Administrador)"
fi
clear
echo "
"
echo -e "\033[1;32m#############################################"
echo -e "
\033[1;36m Usuario: \033[2;37m$user
\033[1;36m Senha: \033[2;37m$senha
\033[1;36m Data de expiração: \033[2;37m$data3/$data2/$data1"
if [ $usernum -eq 0 ]; then
echo -e "
\033[1;36m Status atual(SSH): \033[1;31mOffline
\033[1;36m Limite de conexoes: \033[2;37m$limitecs
\033[1;36m Numero Conexoes Online: \033[1;31m$usernum
"
else
echo -e "
\033[1;36m Status atual(SSH): \033[1;32mOnline
\033[1;36m Limite de conexoes: \033[2;37m$limitecs
\033[1;36m Numero Conexoes Online: \033[1;32m$usernum
"
fi
echo -e "\033[1;36m Status atual(OpenVPN): $status
\033[1;36m Online Desde: \033[2;37m$desde
\033[1;36m IP virtual usuario: \033[2;37m$ipvpn
\033[1;36m Download: \033[2;37m$down
\033[1;36m Upload: \033[2;37m$up

\033[1;36m IP do Servidor OpenVPN: \033[2;37m$IP
\033[1;36m Porta OpenVPN: \033[2;37m$IPVPNPORT1 $IPVPNPORT2 $IPVPNPORT3 $IPVPNPORT4
\033[1;36m IP do Servidor SSH: \033[2;37m$IP
\033[1;36m Porta SSH: \033[2;37m$IPSSHPORT1 $IPSSHPORT2 $IPSSHPORT3 $IPSSHPORT4
\033[1;36m IP da Proxy: \033[2;37m$IP
\033[1;36m Porta Proxy: \033[2;37m$IPPORT1 $IPPORT2 $IPPORT3 $IPPORT4 $IPPORT5 $IPPORT6 $IPPORT7 $IPPORT8

\033[1;36m Criado por: \033[2;37m$ADM
\033[1;36m Data de Criação: \033[2;37m$ADM1 $ADM2
\033[1;36m Ip do criador: \033[2;37m$ADM3
"
echo -e "\033[1;32m#############################################\033[1;0m"
echo "
"
