#!/bin/bash
cd
NUMBEROFCLIENTS=$(cat usuarios.txt|cut -d ":" -f 1|wc -l)
                        if [[ "$NUMBEROFCLIENTS" = '0' ]]; then
                                echo ""
                                echo -e "\033[1;31mVocê não tem usuarios existentes!\033[0m"
                                exit 6
                        fi
                        echo ""
                        echo -e "\033[1;32m Selecione um usuario para remover\033[0m"
                        cat usuarios.txt|cut -d ":" -f 1| nl -s ') '
                        if [[ "$NUMBEROFCLIENTS" = '1' ]]; then
                                read -p "Selecione um usuario [1]: " CLIENTNUMBER
                        else
                                read -p "Selecione um usuario [1-$NUMBEROFCLIENTS]: " CLIENTNUMBER
                        fi
                        CLIENT=$(cat usuarios.txt |cut -d ":" -f 1| sed -n "$CLIENTNUMBER"p)
if (echo $CLIENTNUMBER | egrep '[^0-9]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -gt $NUMBEROFCLIENTS ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -lt 1 ]]; then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
senha=$(cat usuarios.txt|grep -w $CLIENT|cut -d ":" -f 2)
limite=$(cat usuarios.txt|grep -w $CLIENT|cut -d ":" -f 3)
data=$(cat usuarios.txt|grep -w $CLIENT|cut -d ":" -f 4)
clear
echo -e "
\033[44;1;37m    Dados atual do usuario    \033[0m
\033[1;36m Usuarios:\033[1;37m $CLIENT
\033[1;36m Senha:\033[1;37m $senha
\033[1;36m Validade:\033[1;37m $data
\033[1;36m Conexões:\033[1;37m $limite
"
echo -e "
\033[1;37mQual a nova senha do usuario $CLIENT\033[0m"
read -e -i $senha pass
echo -e "\033[1;37mQual a nova data de validade do usuario? Formato \033[1;33mAAAA/MM/DD \033[0m"
read -e -i $data date
echo -e "\033[1;37mQual o novo limite de conexões do usuario? \033[0m"
read -e -i $limite num

if (echo $pass | egrep '[^a-zA-Z0-9]')
then
echo -e "\033[1;31mErro!!\033[0;31m Você digitou uma senha inválida! \033[0m"
exit
else
echo ""
fi
sizemaxpass=$(echo ${#pass})
if [[ $sizemaxpass -gt 9 ]]
then
echo "\033[1;31mErro!! \033[0;31mVocê digitou uma senha muito grande,
 Use no máximo 9 caracteres!\033[0m"
exit
else
echo ""
fi
sizemaxnum=$(echo ${#num})
if [[ $sizemaxnum -gt 2 ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou Limite de Conexoes muito alto,
 É permitido no maximo 99 conexoes!\033[0m"
exit
else
echo ""
fi
if (echo $num | egrep '[^0-9]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número de conexões inválido!\033[0m"
exit
else
echo ""
fi
if (echo $date | egrep '[^0-9/]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou uma data inválida!\033[0m"
exit
else
echo ""
fi
validador=$(cat /clientes/editar|grep -w $CLIENT|cut -d ":" -f 1)
if [[ $validador = $CLIENT ]]; then
sed -i /^$CLIENT/d /clientes/editar
else
echo ""
fi
echo -e "
\033[44;1;37m    Novos dados do usuario    \033[0m
\033[1;32m Usuarios:\033[1;37m $CLIENT
\033[1;32m Senha:\033[1;37m $pass
\033[1;32m Validade:\033[1;37m $date
\033[1;32m Conexões:\033[1;37m $num\033[0m
"
read -p " Deseja editar o Usuario $CLIENT ? [s/n] " -e -i n CONFIRMACAO
echo ""
if [[ "$CONFIRMACAO" = 's' ]]; then
echo ""
else
echo "
 Edição de usuarios abordada!
"
exit
fi
echo "$CLIENT:$pass:$num:$date" >> /clientes/editar
sed -i /^$CLIENT/d usuarios.txt
echo "$CLIENT:$pass:$num:$date" >> usuarios.txt

echo " Solicitado com sucesso!! Nova modificação do usuario $CLIENT será aplicada em 1 minuto"
