#!/bin/bash
mkdir /etc/usuarios 1>/dev/null 2>/dev/null
userrc=$(echo $1 |sed 's/-/k/g' |sed 's/0/a/g' |sed 's/1/b/g' |sed 's/2/c/g' |sed 's/3/d/g' |sed 's/4/e/g' |sed 's/5/f/g' |sed 's/6/g/g' |sed 's/7/h/g' |sed 's/8/i/g' |sed 's/9/j/g')
sustenido=$
limpcron=$(cat /etc/crontab |grep -v /$1.sh)
echo "$limpcron" > /etc/crontab
echo "#!/bin/bash" > /etc/usuarios/$1.sh
echo ""$userrc"t="$sustenido"(ps -u $1 |grep 'sshd' |wc -l)" >> /etc/usuarios/$1.sh
echo "if [ "$sustenido""$userrc"t -gt $2 ]" >> /etc/usuarios/$1.sh
echo "then" >> /etc/usuarios/$1.sh
echo "pid="$sustenido"(ps -u $1 |grep sshd |awk {'print "$sustenido"1'}|head -1)" >> /etc/usuarios/$1.sh
echo kill -9 '$pid' >> /etc/usuarios/$1.sh
echo "fi" >> /etc/usuarios/$1.sh
mkdir /etc/tempo 1>/dev/null 2>/dev/null
echo "#!/bin/bash" > /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "$2" > /etc/VpsPackdir/limite/$1
echo "*/1 * * * * root bash /etc/tempo/$1.sh" >> /etc/crontab
echo -e "\033[1;37mUsuario: \033[1;31m[\033[1;37m$1\033[1;31m]\033[1;37m Limite: \033[1;31m[\033[1;37m$2\033[1;31m] \033[1;37m[\033[1;31mLimite Aplicado\033[1;37m]  \033[0m"
