#!/bin/bash
read -p "Em qual diretorio esta o arquivo de Backup: " arq
clear
#if [ -d $arq ]
#then
#echo ""
#else
#echo "$arq"
#echo -e "
#\033[1;31m Arquivo de Backup não foi encontrado\033[0m
#"
#exit
#fi
echo -e "\033[1;37mRestaurando Usuarios...\033[0m"
for usuario in `cat $arq |awk '{print $1}'`
do
#usuario=$(echo "$user" |awk '{print $1}')
senha=$(cat $arq |grep -w $usuario|awk '{print $2}')
limite=$(cat $arq |grep -w $usuario|awk '{print $3}')
date=$(cat $arq |grep -w $usuario|awk '{print $4}')
ADM=$(cat $arq |grep -w $usuario|awk '{print $5}')
ADM1=$(cat $arq |grep -w $usuario|awk '{print $6}')
ADM2=$(cat $arq |grep -w $usuario|awk '{print $7}')
ADM3=$(cat $arq |grep -w $usuario|awk '{print $8}')
ADM4=$(cat $arq |grep -w $usuario|awk '{print $9}')
if [[ $ADM4 = "" ]]; then
echo -e "
\033[1;31m Erro!! Arquivo de Backup esta corrompido\033[0m
"
exit
else
echo "" > /dev/null
fi
if cat /etc/passwd |grep -w $usuario: 1> /dev/null 2>/dev/null
then
echo " " > /dev/null
else
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  limit $usuario $limite 1> /dev/null 2> /dev/null
  echo "$senha" > /etc/VpsPackdir/senha/$usuario
  chage -E $date $usuario 2> /dev/null
  echo "$date" > /etc/VpsPackdir/date/$usuario
echo "$ADM $ADM1 $ADM2 $ADM3 $ADM4" > /etc/VpsPackdir/UsuariosADM/$usuario
  echo -e "\033[1;37mUsuario: \033[1;31m$usuario \033[1;37mBackup: [\033[1;31mOk\033[1;37m]\033[0m"
fi
done
