#!/bin/bash
NUMBEROFCLIENTS=$(awk -F : '$3 > 900 ' /etc/passwd |grep -vi /bin/false|grep -vi "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]|awk -F : '{ print $1 }'|sort)
if [[ "$NUMBEROFCLIENTS" = '0' ]]; then
echo ""
echo -e "\033[1;31mVocê não tem usuarios existentes!\033[0m"
exit 6
fi
awk -F : '$3 > 900 ' /etc/passwd |grep -vi /bin/false|grep -vi "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]|awk -F : '{ print $1 }'|sort|nl -s ") "
 if [[ "$NUMBEROFCLIENTS" = '1' ]]; then
 read -p "Selecione um usuario [1]: " CLIENTNUMBER
 else
 read -p "Selecione um usuario [1-$NUMBEROFCLIENTS]: " CLIENTNUMBER
 fi
 name=$(awk -F : '$3 > 900 ' /etc/passwd |grep -vi /bin/false|grep -vi "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]|awk -F : '{ print $1 }'|sort|sed -n "$CLIENTNUMBER"p)
if (echo $CLIENTNUMBER | egrep '[^0-9]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -gt $NUMBEROFCLIENTS ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -lt 1 ]]; then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
echo ""
read -p " Deseja Revover o Usuario $name ? [s/n] " -e -i n CONFIRMACAO
echo ""
if [[ "$CONFIRMACAO" = 's' ]]; then
echo ""
else
echo "
 Remoção abordada!
"
exit
fi
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
rm /etc/VpsPackdir/UsuariosADM/$name /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 read -p "Deseja apagar a pasta clientes do usuario $name ? [s/n] " resposta
if [[ "$resposta" = 's' ]]; then
 rm -r /clientes/$name /dev/null 2>/dev/null
 else
 echo ""
 fi 
 echo "Usuario $name foi deletado e parado"



