#!/bin/bash

read -p "Qual o nome do usuario a redefinir: " name
if cat /etc/passwd |grep $name: > /dev/null
then
echo " "
else
echo " "
echo -e " \033[0;31mUsuario $name não existe\033[0m"
echo " "
exit
fi
clear
echo " "
echo " "
echo -e "\033[44;1;37m O que vc deseja redefinir ?\033[0m
\033[1;32m
  1) Numero de logins
  2) Data de expiraçao
  3) Mudar senha do usuario
  4) Deletar usuario
  5) Deletar e desconectar todos do usuario
  6) Desconectar todos do usuario\033[0m"

read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$name.sh
rm /etc/tempo/$name.sh
limit $name $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Qual a nova data : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $name 2> /dev/null
echo -e "\033[0;31mUsuario $name Date: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Qual a nova senha para $name: " senha
(echo "$senha" ; echo "$senha" ) |passwd $name > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$name
echo "Nova senha aplicada"
exit
fi

 if [ $option -eq 4 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh
 rm /etc/tempo/$name.sh
 rm /etc/VpsPackdir/limite/$name
 rm /etc/VpsPackdir/senha/$name
 rm /etc/VpsPackdir/date/$name
 echo "Usuario $name foi deletado"
 exit
 fi

 if [ $option -eq 5 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh
 rm /etc/tempo/$name.sh
 rm /etc/VpsPackdir/limite/$name
 rm /etc/VpsPackdir/senha/$name
 rm /etc/VpsPackdir/date/$name
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi deletado e parado"
 exit
 fi

 if [ $option -eq 6 ]; then
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi parado"
 exit
 fi

echo -e "\033[1;31messa opçao não existe\033[0m"
