#!/bin/bash
clear
echo "-------------------------------------------------------
 Usuario       Senha       SSH    Data C.      Data E.
-------------------------------------------------------"

for users in `cat /etc/expireduser.txt|awk '{print $3}'|sort`
do
if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi
if (cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi
data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
dataxp=$(cat /etc/expireduser.txt |grep -w $users|awk -F : '{print $3}'
detalhesdata=$(printf '%-13s' "$data")
detalhesdataxp=$(printf '%-13s' "$dataxp")
detalheslimit=$(printf '%-4s' "$limitecs")
detalhes=$(printf ' %-13s' "$users")
detalhespass=$(printf '%-14s' "$senha")
echo -e "\033[1;33m$detalhes $detalhespass $detalheslimit $detalhesdata $detalhesdataxp"
echo -e "\033[1;30m-------------------------------------------------------\033[0m"
done
total=$(cat /etc/expireduser.txt|awk '{print $3}'|sort|wc -w)
echo -e "\033[1;32m Total de Usuarios: $total\033[0m"
