#!/bin/bash
NUMBEROFCLIENTS=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort|wc -l)
if [[ "$NUMBEROFCLIENTS" = '0' ]]; then
echo ""
echo -e "\033[1;31mVocê não tem usuarios existentes!\033[0m"
exit 6
fi
echo -e "\033[44;1;37m        Redefina um Usuário          \033[0m"
awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort |nl -s ") "
 if [[ "$NUMBEROFCLIENTS" = '1' ]]; then
 read -p "Selecione um usuario [1]: " CLIENTNUMBER
 else
 read -p "Selecione um usuario [1-$NUMBEROFCLIENTS]: " CLIENTNUMBER
 fi
name=$(awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system- |grep -vi openvpn|sort| sed -n "$CLIENTNUMBER"p)
if (echo $CLIENTNUMBER | egrep '[^0-9]')
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -gt $NUMBEROFCLIENTS ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
if [[ $CLIENTNUMBER -lt 1 ]]; then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número inválido!\033[0m"
exit
else
echo ""
fi
clear
echo " "
echo " "
echo -e "\033[44;1;37m O que vc deseja redefinir para \033[1;33m$name \033[44;1;37m?\033[0m
\033[1;32m
  1) Numero de logins
  2) Data de expiraçao
  3) Mudar senha do usuario
  4) Deletar usuario
  5) Deletar e desconectar todos do usuario
  6) Desconectar todos do usuario\033[0m"
echo " "
read -p "opção [1-6]: " option

if [ $option -eq 1 ]; then
echo $name > "/etc/cache202.sh"
UserRedefine.op1
exit
fi

if [ $option -eq 2 ]; then
echo $name > "/etc/cache202.sh"
UserRedefine.op2
exit
fi

if [ $option -eq 3 ]; then
echo $name > "/etc/cache202.sh"
UserRedefine.op3
exit
fi

 if [ $option -eq 4 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
rm /etc/VpsPackdir/UsuariosADM/$name /dev/null 2>/dev/null
 echo "Usuario $name foi deletado"
 exit
 fi

 if [ $option -eq 5 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 rm /etc/usuarios/$name.sh /dev/null 2>/dev/null
 rm /etc/tempo/$name.sh /dev/null 2>/dev/null
 rm /etc/VpsPackdir/limite/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/senha/$name /dev/null 2>/dev/null
 rm /etc/VpsPackdir/date/$name /dev/null 2>/dev/null
rm /etc/VpsPackdir/UsuariosADM/$name /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi deletado e parado"
 exit
 fi

 if [ $option -eq 6 ]; then
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuario $name foi parado"
 exit
 fi
echo -e "\033[1;31mEsta opcao nao existe\033[0m"
