#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

clear
echo -e "\033[1;37m VpsPacket © Script criado por: \033[2;32mMatheus Larcher \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] Limit \033[2;36m(limite de conexoes simultaneas)\033[1;34m
[2] UserCreate \033[2;36m(Criar usuarios)\033[1;34m
[3] UserRedefine \033[2;36m(Opções para mudanças no usuario)\033[1;34m
[4] UserBack \033[2;36m(Deletar, Desconectar, Opções)\033[1;34m
[5] Firewall-block \033[2;36m(Regras iptables block torrent, icmp [RISCOS])\033[1;34m
[6] ResetFirewall \033[2;36m(Retira todas as regras iptables [RISCOS])\033[1;34m
[7] Istall-addhosts \033[2;36m(Faz a preparaçao para add-host)\033[1;34m
[8] Add-host \033[2;36m(Adicionar hosts aceitos pelo squid )\033[1;34m
[9] Monitoring \033[2;36m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;34m
[10] Backup-Users \033[2;36m(Backup dos usuarios para reinstalação futura)\033[1;34m
[11] Rest-Users \033[2;36m(Restaurar usuarios feito backup)\033[1;34m
[12] Detalhes-Users \033[2;36m(Mostra informações sobre os usuarios !!)\033[1;34m
[13] Banner \033[2;36m(Banner mensagem no ssh)\033[1;34m
[14] Speedtest \033[2;36m(Teste de conexão [velocidade de banda])\033[1;34m
[15] System-Detalhes \033[2;36m(Detalhes sobre o Sistema)\033[1;34m
[16] Detalhes \033[2;36m(Detalhes sobre o VpsPack)\033[1;34m
read -p ": " opcao

case $opcao in
 1)
  read -p "Usuario: " user
  read -p "Limite de Conexoes: " limit
  limit $user $limit;;
 2)
  Usercreate;;
 3)
  UserRedefine;;
 4)
  UserBack;;
 5)
  firewall-block;;
 6)
  ResetFirewall;;
 7)
  install-addhost;;
 8)
  add-host;;
 9)
  Monitoring;;
 10)
  backupusers;; 
 11)
  read -p "Em qual diretorio esta o arquivo de Backup: " arq 
  restusers $arq;;
 12)
  detalhesusers;;
 13)
  banner;;
 14)
  speedtest;;
 15)
  systemdetalhes;;
 16)
  Detalhes;;
 *)
  id > /dev/null 2> /dev/null
esac
