#!/bin/bash

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi

if [ -d /etc/VpsPackdir/date ]
then
echo ""
else
mkdir /etc/VpsPackdir/date
fi

clear
echo -e "\033[1;37m VpsPacket © Script criado por: \033[2;32mMatheus Larcher \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;34m
[1] UserCreate \033[2;36m(Criar usuarios)\033[1;34m
[2] UserRedefine \033[2;36m(Opções para mudanças no usuario)\033[1;34m
[3] Firewall-block \033[2;36m(Regras iptables block torrent, icmp [RISCOS])\033[1;34m
[4] ResetFirewall \033[2;36m(Retira todas as regras iptables [RISCOS])\033[1;34m
[5] istall-badVPN \033[2;36m(Instalar badVPN para encaminhamento UDP)\033[1;34m
[6] Istall-addhosts \033[2;36m(Faz a preparaçao para add-host)\033[1;34m
[7] Add-host \033[2;36m(Adicionar hosts aceitos pelo squid )\033[1;34m
[8] Backup-Users \033[2;36m(Backup dos usuarios para reinstalação futura)\033[1;34m
[9] Rest-Users \033[2;36m(Restaurar usuarios feito backup)\033[1;34m
[10] Monitoring \033[2;36m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;34m
[11] Detalhes-Users \033[2;36m(Mostra informações sobre os usuarios !!)\033[1;34m
[12] Detalhes-User \033[2;36m(Mostra informações de um unico usuarios)\033[1;34m
[13] Banner \033[2;36m(Banner mensagem no ssh)\033[1;34m
[14] Speedtest \033[2;36m(Teste de conexão [velocidade de banda])\033[1;34m
[15] System-Detalhes \033[2;36m(Detalhes sobre o Sistema)\033[1;34m
[16] Detalhes \033[2;36m(Detalhes sobre o VpsPack)\033[1;34m
[17] Atualizar \033[2;36m(Remover o VpsPack)\033[0m"
read -p ": " opcao

case $opcao in
 1)
  Usercreate;;
 2)
  UserRedefine;;
 3)
  firewall-block;;
 4)
  ResetFirewall;;
 5)
  install-badVPN;;
 6)
  install-addhost;;
 7)
  add-host;;
 8)
  backupusers;;
 9)
  read -p "Em qual diretorio esta o arquivo de Backup: " arq
  restusers $arq;;
 10)
  Monitoring;;
 11)
  detalhesusers;;
 12)
 detalhesuser;;
 13)
  banner;;
 14)
  speedtest;;
 15)
  systemdetalhes;;
 16)
  Detalhes;;
 17)
  Atualizar;;
 *)
  id > /dev/null 2> /dev/null
esac
